### ISSUE TITLE
Every map I create breaks the game

### ISSUE THREAD

**Issue by widardd** [FortuneStreetModding/FortuneAvenue#25] opened 2020-12-23 22:42 UTC
This is probably the completely wrong place to post this, but I don't know how else to give feedback.

I've tried creating 2 maps by now, both break the game in different ways while respecting the documented limitations. (I think)

I've tried v8 aswell as beta v9.

[alephgard.frb](https://drive.google.com/file/d/18WZniLZpPdwqXc45qSyRhJgP33xZRyeR/view?usp=sharing) (game freezes immediately after the frist dice roll)

[dahma.frb](https://drive.google.com/file/d/1wJ9p9hc_zKkZItgP1--5FTdRiLyIuv6k/view?usp=sharing) (game freezes the moment a player hits a warp field)

On dahma.frb I've tried doing basically the same thing before via doors and that lead to the game freezing.
It feels like there's something wrong with pipes/warps/doors.

Would love to create a lot of maps in the future and add them to the community maps branch.

Any help would be greatly appreciated, thank you so much for picking this project up!

**Comment by Deflaktor** [comment] 2020-12-26 17:56
You can take a look at the user guide on how to create maps: https://github.com/FortuneStreetModding/FortuneAvenue/wiki/Fortune-Avenue-User-Guide 

You can ask regarding help with the map editor in the discord communities https://discord.gg/DE9Hn7T or https://discord.gg/23FyBYV 

Other than that there are several issues with the frb files you presented. In alephgard.frb there are waypoints pointing to the bank but the bank has no waypoint entries from these places. Also there are tiny loops possible by going the squares 0 -> 34 -> 1 -> 0 -> 34 -> ...  Tiny loops generally crash the game. You should try to create a map where it is not possible to get to the same square within the same turn. This is just a rule of thumb as it is not clear yet what the exact requirements are so that the game does not crash.

Since this is not a bug with map editor, Im closing this. Please ask in the discord communities in the future.

**Closed as completed by Deflaktor** 2020-12-26 17:56 UTC
